### ISSUE TITLE
About ES6 imports

### ISSUE THREAD

**Issue by epayet** [kpdecker/jsdiff#103]
I played around imports in a node app and experimented this:

```javascript
import diff from 'diff'
console.log(diff) // logs undefined

console.log(require('diff')) // works fine

import { diffChars } from 'diff'
console.log(diffChars) // works fine
```

Is it an expected behaviour that `import diff from 'diff'` gives undefined? I thought it would work like `var diff = require('diff')`.

I managed to get it working by doing `import { diffChars } from 'diff'` but I just wanted to know it was expected to behave like for the default export, I wasn't expecting it.

I am using babel.

Thanks

**Comment by kpdecker** [comment]
Since this is exporting a es6 module and there is no default export, you have to do `import * as diff from 'diff';` to have the same effect. This is masked by most commonjs modules as babel implements a adapter layer to try to map common js to the default export.
