### ISSUE TITLE
Release File

### ISSUE THREAD

**Issue by paragonie-scott** [kpdecker/jsdiff#104]
For folks that don't have `npm` installed, could we get a `.js` (and, optionally, `.min.js`) uploaded with the Github releases?

Some CDNs offer jsdiff, but not a recent version. For example: http://www.jsdelivr.com/projects/jsdiff

**Comment by kpdecker** [comment]
https://github.com/components/jsdiff

**Comment by Atulin** [comment]
components/jsdiff is still on 3.4.0, while the main repo already entered 4.0.2
