### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by adius** [kpdecker/jsdiff#107]
I was searching for `diff` on github, but didn't find this repository.
I guess the diff keyword should be used somewhere so that this repo can be found
(as well as `patch`)

**Comment by isiahmeadows** [comment]
In my experience, GitHub sucks when it comes to searching for projects, and most of the time I use its project search feature, it's purely inadvertent. Also, npm is often better than even Google when it comes to searching for modules. If you search `diff` on npm, this is literally the first module to come up, BTW.

**Comment by kpdecker** [comment]
Not really something that I wish to spend time or money on and I have no clue what SEO in github would look like.

**Comment by adius** [comment]
Just use the keyword `diff` somewhere in the readme or project description.
That's all I'm asking for 🙈

**Comment by kpdecker** [comment]
There are numerous mentions of diff in the readme.

**Comment by adius** [comment]
Ok, then it must occur in the project description.

The point is I would expect/want to find jsdiff while searching for javascript diff programs: https://github.com/search?utf8=%E2%9C%93&q=language%3Ajavascript+diff

…but it's not among the results!
