### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by adius** [kpdecker/jsdiff#108]
I'm always getting following error:

```
TypeError: Cannot read property 'diffChars' of undefined
```

Does this maybe happen because I use babel (preset-es2015) to compile all my code?

**Comment by adius** [comment]
yes, that's the problem.

`const diff = require('diff')` works and `import diff from 'diff'` doesn't 😩

**Comment by noBlubb** [comment]
Seems to be (almost) the same issue as #103

**Comment by kpdecker** [comment]
@adius did `import * as diff from 'diff'` work?

**Comment by adius** [comment]
@kpdecker Yeah, If I remember correctly that fixed it.
