### ISSUE TITLE
Feature request: JsDiff.serializePatch(structuredPatch)

### ISSUE THREAD

**Issue by adius** [kpdecker/jsdiff#109]
What do you think about adding a `JsDiff.serializeStructuredPatch(structuredPatchObject)` method,
which is basically the reverse of `JsDiff.parsePatch(diffStr)`.

I'd even provide a pull request =P

**Comment by kpdecker** [comment]
Name is a little bit lengthy, but glad to review and PRs sent in.

**Comment by RonWang** [comment]
@kpdecker How do we generate the diffStr out now? Does it come from structuredObject?

**Comment by ExplodingCabbage** [comment]
Hmm. It looks to me like the `formatPatch` method we *already* export from `patch/create.js` essentially _is_ the `serializePatch` method contemplated here, and all I need to do is

1. add tests showing it's the inverse of `parsePatch`
2. expose it on the top-level `Diff` object exported by the library, and
3. document it

I would also prefer `serializePatch` as a name over `formatPatch` but I suppose it doesn't matter much so I'll just keep the old name for consistency.
