### ISSUE TITLE
Partially apply a patch?

### ISSUE THREAD

**Issue by vmazare** [kpdecker/jsdiff#112]
I am not sure if this is a feature request or an issue so I am sorry in advance.
Is there a possibility to select which changes from a specific patch I want to apply? A good example of what I mean is GitHub Desktop. I try to implement a similar solution using `jsdiff` but as far as I've seen it doesn't look possible. 

Patch example: 

```
1 - var a = 1
2 - var h = 0
3 - var b = 3
1+ //comment
2+ //comment longer 
3+ // abc
4+ // abcdffdgdfgdfg

```

Let's say for now I only want to apply the `deletion from line 1` and `addition from line 4`.
Any ideas? Thank you.

**Comment by kpdecker** [comment]
I would look at the structured patch format and then try to filter the data in there to fit your needs. I'm not certain that this will work but you can give it a shot. If you come up with something that is generic, then I'd be glad to review a PR!

**Comment by vmazare** [comment]
I am already testing a solution which seems to be working. I might create a PR in a couple days. Thanks.
