### ISSUE TITLE
/patch/merge not exported

### ISSUE THREAD

**Issue by saimeunt** [kpdecker/jsdiff#114]
For some reason you implemented 3 way merge (which is pretty cool) as a feature request that landed in 2.1.0 but you do not export it from the main entry point (src/index.js).

Please add the required patch :

`import {merge} from './patch/merge';`

`export {merge};`

And publish a new version on npm.

**Comment by christophepas** [comment]
Hey ! Is there any plan to release this feature in the near future ?

Thanks !

**Comment by kpdecker** [comment]
Pull requests accepted.

**Comment by snadrus** [comment]
#165
