### ISSUE TITLE
TypeError: value.split is not a function

### ISSUE THREAD

**Issue by Nibor808** [kpdecker/jsdiff#122]
I have 2 files that I'm trying to read and get the diff:

 cNew = './htmlLog/clog'
 oldhtmlPlus ='./htmlLog/log'
 contentOld = fs.readFileSync(oldhtmlPlus)
 contentNew = fs.readFileSync(cNew)
 diff = jsdiff.diffTrimmedLines(contentOld, contentNew)

However I keep getting the error TypeError: value.split is not a function?

**Comment by kpdecker** [comment]
contentOld and contentNew are Buffers. You need to toString them or pass an
encoding to the read functions to ensure that they are a string.

**Comment by Nibor808** [comment]
That got it thank you.
