### ISSUE TITLE
"TypeError: value.split is not a function" when one parameter is an object

### ISSUE THREAD

**Issue by wolfie** [kpdecker/jsdiff#123]
I'm getting the following error when with diff 2.2.3, Node.js v6.2.0 (and npm 3.8.9):

```
[...]/node_modules/diff/lib/diff/line.js:22
      linesAndNewlines = value.split(/(\n|\r\n)/);
                               ^

TypeError: value.split is not a function
    at Object.lineDiff.tokenize ([...]/node_modules/diff/lib/diff/line.js:22:32)
```

I'm trying to call the `diffLines` function with two string parameters.

**Comment by wolfie** [comment]
Actually, both parameters _weren't_ strings - one was a ES6 class object. When I made sure that both parameters were objects, I don't get this message anymore.

I'll update the subject...

**Comment by kpdecker** [comment]
You can only diff strings with diffLines.

**Comment by wolfie** [comment]
That is quite understandable.

My issue is that the error message is not user friendly. The problem is not that MyClass doesn't have a split function, but rather that the given parameter was something that the library didn't expect.

**Comment by kpdecker** [comment]
Adding such sanity checking code adds overhead on the wire with little benefit for production, so it's something that we want to avoid.
