### ISSUE TITLE
IE7/IE8 failure since 2.0.0

### ISSUE THREAD

**Issue by boneskull** [kpdecker/jsdiff#124]
Hi,

In the process of trying to update [mocha](/mochajs/mocha)'s dependencies, I found diff >= 2.0.0 breaks in IE8.

This is why:

```js
exports.default = Stuff;
```

`default` cannot be used this way in IE8.  It *can* be used like this:

```js
exports['default'] = Stuff;
```

I did find [this module](https://github.com/coudly/babel-plugin-transform-es3-modules-literals), but I couldn't get it to work.

**Comment by kpdecker** [comment]
This is an artifact of the babel setup. I don't really have time to look at the config to fix this right now, but I'm glad to accept pull requests.

**Comment by boneskull** [comment]
Yeah, interested in a fix as well so Mocha can upgrade, but I'm in same boat

**Comment by kpdecker** [comment]
Released in 3.0.1
