### ISSUE TITLE
Make `applyPatches` patched callback async

### ISSUE THREAD

**Issue by piranna** [kpdecker/jsdiff#129]
On `applyPatches()` functions the `loadFile()` option accept a callback that must be called with the content of the file to be patched, but the `patched()` option don't, forcing to implement it as a sync function. Ironically, [just in the next line](https://github.com/kpdecker/jsdiff/blob/4a899c0afc95228d20b6b743ce9ea45e4233d60e/src/patch/apply.js#L140-L142) there's a `setTimeout(processIndex, 0)` to process the next index!

What I propose is to add a callback argument to `patched()` function so it can both notify when it has finished and can start processing the next index, and also if there was an error while writting the patch. A more advanced option would be to use `async.js` for that, that's already a dependency and would make the code a bit cleaner.

**Comment by kpdecker** [comment]
Closing in favor of #130
