### ISSUE TITLE
Including jsdiff in a bundle adds distance-iterator.js to stack traces

### ISSUE THREAD

**Issue by callmevlad** [kpdecker/jsdiff#132]
This is admittedly vague, but adding `diff` (at least the last 2 versions) inside of a bundle causes `distance-iterator.js` to appear repeatedly inside call stacks despite those errors happening in completely unrelated code:

![image](https://cloud.githubusercontent.com/assets/785166/17863027/c95a4fcc-684c-11e6-915d-904e5948975d.png)

Any tips whether there's anything custom going on in this library in terms of trying to preserve source maps non-natively somehow?

**Comment by callmevlad** [comment]
Wondering if this has anything to do with the function https://github.com/kpdecker/jsdiff/blob/master/src/util/distance-iterator.js#L4 not defining a name in the export. I'll test locally and submit a PR if that's the case.

**Comment by callmevlad** [comment]
@kpdecker Any tips on how to test the generation of the source maps locally? Apologies for the noob question.

**Comment by ExplodingCabbage** [comment]
Hmm. I wonder if this issue from 2016 is still relevant today? Alas I have no idea how to even begin attempting to reproduce the issue, so I can't find out.

I'd be happy to try to debug this if anyone can give me steps to reproduce, but until then I'm going to close this.
