### ISSUE TITLE
missing dist/diff.js

### ISSUE THREAD

**Issue by Ruplahlava** [kpdecker/jsdiff#134]
Hello,
its seems that there is no built diff for simple web page :(

Can you please built it and add it? (Web example also not working...)

**Comment by charlie-wasp** [comment]
You can install it via npm somewhere, and then just copy builded file. I did so :)

**Comment by kpdecker** [comment]
We actively do not include build artifacts in source as it creates problems when merging. npm is our "source of truth" for released versions of the project.

**Comment by JamoCA** [comment]
I came here looking for the "dist" directory too.  (I don't use NPM.)

It appears that you can download the distribution JS from CDNJS.
https://cdnjs.com/libraries/jsdiff
