### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by sapegin** [kpdecker/jsdiff#138]
Because [it’s important](https://medium.com/@sapegin/add-the-fucking-change-log-3d82d758d8b0).

**Comment by kpdecker** [comment]
I fucking agree: https://github.com/kpdecker/jsdiff/blob/master/release-notes.md

**Comment by sapegin** [comment]
`release-notes.md` is very unusual name. I’m sure I’m not the first who couldn’t find it. `History.md` or `Changelog.md` would be much better.
