### ISSUE TITLE
Flip added and removed order?

### ISSUE THREAD

**Issue by jakesandlund** [kpdecker/jsdiff#14]
I'm wondering if it would make sense to flip the order in which added vs removed change objects get returned `diffLines`. This would make it easier to make a "git-like" diff without having to swap the added and removed semantics.

This is what I'm doing right now for [Vaccine](http://www.vaccinejs.com/):

```javascript
var chunks = jsdiff.diffLines(next, old).map(function(d) {
  if (d.removed) {
    return '<span class="added">' + prepend(d.value, '+') + '</span>';
  } else if (d.added) {
    return '<span class="removed">' + prepend(d.value, '-') + '</span>';
  } else {
    return prepend(d.value, ' ');
  }
});
return chunks.join('\n');
```

**Comment by monsanto** [comment]
+1 this was surprising to me

**Comment by nylen** [comment]
+1 to this, as a result [`mocha`](https://github.com/mochajs/mocha) displays diffs in the reverse order from standard tools like `diff` and `git`.

**Comment by kpdecker** [comment]
Released in 1.4.0

**Comment by nylen** [comment]
:+1: thanks!!

**Comment by mathiasrw** [comment]
Yayyyy :)
