### ISSUE TITLE
Cannot apply patch because my file delimiter is "/r/n" instead of "/n"

### ISSUE THREAD

**Issue by soulbeing** [kpdecker/jsdiff#141]
My target file(the one going to apply the patch) has "/r/n" as line delimiter, so because in the apply.js at line 32 you hard coded to separate the file with "/n", and this will result in "false" returned from compareLine method, and the patch generated from "git diff" command cannot be applied to my file. Any action will take on this?

**Comment by soulbeing** [comment]
it's on Window btw,

**Comment by soulbeing** [comment]
fixed in my pull request

**Comment by alexdrans** [comment]
Hey @soulbeing, did this ever make it in? `diffLines` also doesn't work for Windows line endings (on  OS X). Going to investigate now.
