### ISSUE TITLE
Components releases are missing since 2.2.3

### ISSUE THREAD

**Issue by sfnelson** [kpdecker/jsdiff#147]
Did someone forget to run the last step of the release?

```
yo release:publish components jsdiff dist/components/
```

https://github.com/components/jsdiff

**Comment by kpdecker** [comment]
3.1.0 has been released on the bower distro. Moving forward, I may desupport this as bower's selling points are less and less in the npm3 and webpack world.

**Comment by sfnelson** [comment]
The components/bower build is currently useful for including jsdiff from Clojurescript using the Google Closure compiler (https://github.com/cljsjs/packages/tree/master/jsdiff). Could you suggest an alternative approach, if the bower build is going away?
