### ISSUE TITLE
Add an option to return one change object per token (e.g. a single line per change object when comparing lines)

### ISSUE THREAD

**Issue by hubgit** [kpdecker/jsdiff#148]
When using `diffLines` to compare two versions of a text, would it be possible for each `change` object to only contain a single line, rather than merging consecutive lines into a single `change` object?

**Comment by Ohar** [comment]
Can it helps you?

> newlineIsToken: true to treat newline characters as separate tokens. This allows for changes to the newline structure to occur independently of the line content and to be treated as such. In general this is the more human friendly form of diffLines and diffLines is better suited for patches and other computer friendly output.

**Comment by leviwheatcroft** [comment]
I don't know what 'newlineIsToken' actually does, but it doesn't seem to split changes into lines.

**Comment by ExplodingCabbage** [comment]
No reason for this to be specific to `diffLines`; it would just as well make sense to have one change object per word in `diffWords`, or one change object per character in `diffChars`. And yeah, adding an option for that makes sense to me!

**Comment by ExplodingCabbage** [comment]
Fix ready to go out in the release after next. (Had to implement this on top of some *breaking* changes to make it not be a nightmare, which is why it won't be in the next release.)
