### ISSUE TITLE
Option to take in account undefined values in `diffJson`

### ISSUE THREAD

**Issue by ewnd9** [kpdecker/jsdiff#155]
I'm using `jsdiff` to show a diff if two objects are not equal. 
 
```js
const { diffJson } = require('diff');
const isEqual = require('lodash.isequal');

check({ x: 1, y: undefined }, { x: 1 });

function check(expected, actual) {
  if (!isEqual(expected, actual)) { //=> false
    console.log(diffJson(expected, actual)); //=> [ { value: '{\n  "x": 1\n}', count: 3 } ]
  }
}
```

Now it's ignoring `undefined` value due to default `JSON.stringify` behaviour. 
I propose to add an option to `diffJson` method to show changes. The simplest way I found is to add a custom `replacer` function (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in `JSON.stringify` (see https://github.com/ewnd9/jsdiff/commit/c6daea71b07e660870a6e81b58b7d487fac1cb52) 

I would love to make a PR if the change is welcomed

**Comment by kpdecker** [comment]
Sounds good if you want to PR
