### ISSUE TITLE
Make wordDiff available on import

### ISSUE THREAD

**Issue by gdavoianb** [kpdecker/jsdiff#169]
Is it possible to make internal objects like `wordDiff` importable and available via `jsdiff` module? I think it makes sense, for example, because sometimes I want to implement my custom diffs, but don't want to **rewrite** `tokenize` completely, instead I want to get new tokens by tweaking the **base implementation**.  So importing only `diffWords` is not flexible and extendable enough, and actually restricts the usage of the library.

**Comment by dawadam** [comment]
You can use that in the meantime :

`var jsdiff = require('diff')`

**Comment by Niels-NTG** [comment]
I think this issue can be considered as resolved, since you can now import every type of diff function individually.

**Comment by ExplodingCabbage** [comment]
With the version of `jsdiff` on master, you can do

```
require("diff/lib/diff/word.js").wordDiff
```

This was broken for a while, but https://github.com/kpdecker/jsdiff/pull/351 fixed it. (The fix isn't in any release on npm yet, but will be in due course.)
