### ISSUE TITLE
`import JsDiff from 'diff'` doesn't work.

### ISSUE THREAD

**Issue by kud** [kpdecker/jsdiff#170]

**Comment by kud** [comment]
`import * as differ from 'diff'`

Thanks. ;)

**Comment by SuperKiwi** [comment]
Thank you @kud I was also looking for that. 
Out of curiosity, how / where did you find out the answer ?

**Comment by kud** [comment]
@SuperKiwi https://github.com/kpdecker/jsdiff/blob/master/src/index.js#L36-L61 this is what is exported.
