### ISSUE TITLE
Any option not to catch unbreakable space?

### ISSUE THREAD

**Issue by kud** [kpdecker/jsdiff#174]
Hello,

I'm using `wordsWithSpace` function to make the diff but I'd like not to catch unbreakable spaces. Is there any option to do that?

For the moment I do this:

```javascript
    /* remove unbreakable space */
    const original = this.props.original.replace(/ /gi, ' ')
    const changed = this.props.changed.replace(/ /gi, ' ')

    const differential = diffFnMap[this.props.type](original, changed)
```

**Comment by ExplodingCabbage** [comment]
As in, you'd like a version of `diffWordsWithSpace` that treats whitespace changes as changes *except* for changes where spaces are converted to non-breaking spaces, or vice versa, in which case you want the strings to be treated as identical?

There's of course no option *specifically* for that highly specific task, nor would I want to add one. But you could in principle do this by extending `wordDiff` with a tweaked `equals` method. We don't have got docs on defining custom differs right now, but we've got an issue to add such docs (https://github.com/kpdecker/jsdiff/issues/149) which I'll get to at some point.
