### ISSUE TITLE
Apply patch doesn't work as expected when removing all contents of a file

### ISSUE THREAD

**Issue by dolftax** [kpdecker/jsdiff#177]
### Diff 
```
===================================================================
--- index.js
+++ index.js
@@ -1,3 +1,0 @@
-this
-
-tos
\ No newline at end of file
```

### Local file content before applying the patch
```
this

tos
```

### Local file content after applying the patch
```
this
```

FYI, fuzzFactor is zero.

**Comment by dolftax** [comment]
Also, applyPatch is returning `false` boolean at times.

**Comment by piranna** [comment]
Seems an off-by-one counting, probably related to my problem at #189.
