### ISSUE TITLE
How to use the ignorecase option in the diffChars method

### ISSUE THREAD

**Issue by xerosanyam** [kpdecker/jsdiff#178]
Please specify how to use the method, I am unable to use the `ignoreCase` parameter
I am using it in the browser. ie without node
thanks

**Comment by olafthiele** [comment]
Was just wondering, some testing reveals: 

Diff.diffChars("ME", "me", {ignoreCase : true})

**Comment by xerosanyam** [comment]
Thanks for the reply, this issue is quite old, closing.
