### ISSUE TITLE
JsDiff newline trouble

### ISSUE THREAD

**Issue by coderaiser** [kpdecker/jsdiff#18]
Hello,
thank you for good library :). It's very useful. I'm using it in my [project](http://cloudcmd.io).

I have trouble with applying patch of JsDiff on windows and linux.

server works on linux:

``` js
Index: cloudcmd.js
===================================================================
--- cloudcmd.js
+++ cloudcmd.js
@@ -1,5 +1,5 @@
+(function(){a
-(function(){
     'use strict';

     var DIR         = __dirname     + '/',
         main        = require(DIR   + 'lib/server/main'),
```

server works on windows:

``` js
Index: cloudcmd.js
===================================================================
--- cloudcmd.js
+++ cloudcmd.js
@@ -1,5 +1,5 @@
+(function(){a
-(function(){
\ No newline at end of file

     'use strict';

     var DIR         = __dirname     + '/',

```

As you see on windows OS there is an "\ No newline at end of file" string. I think that it's a reason why patch do not applying on windows.
For edeting text files I'm using [Ace](http://ace.ajax.org).

Can you help me please to figure out what's is going on.

**Comment by subashappvance** [comment]
Can someone share me diff.js file
