### ISSUE TITLE
[Regression] Bad merge when adding new files

### ISSUE THREAD

**Issue by piranna** [kpdecker/jsdiff#189]
When adding a new file, first line of new file is removed from file beggining and added at the end of the new file, corrupting data. This works correctly with diff 3.0.1, so it got broken in some moment after that.

**Comment by piranna** [comment]
Doing a `git bisect` it shows the regression was added at https://github.com/kpdecker/jsdiff/commit/d8a363516ec35462998b407adcd710c0a2d21365

**Comment by piranna** [comment]
I'm having troubles to fix the regression... reverting the changes my test works but the added ones fails, adding the changes to the end. @tyomitch, can you help here?

**Comment by tyomitch** [comment]
@piranna would you try https://github.com/kpdecker/jsdiff/pull/192

**Comment by piranna** [comment]
> @piranna would you try #192

Tests seems to pass, do you ask that I try it on real code?

**Comment by tyomitch** [comment]
Yes, on whatever alerted you of this bug in the first place.

**Comment by piranna** [comment]
> Yes, on whatever alerted you of this bug in the first place.

Ok, I tried it on https://github.com/piranna/BarebonesOS-linux and it failed :-(

**Comment by tyomitch** [comment]
@piranna how do I reproduce the failure with `BarebonesOS-linux`?
`npm install` succeeds for me, then `npm run build` fails saying "missing script: build" (and it's indeed missing).

**Comment by piranna** [comment]
@tyomitch it was my fault, I was using an in-development version of `BarebonesOS-linux` that in fact was not working. I re-check it again with master and it works, so I can confirm that your pull-requests fix the regression also on real world code. I propose to merge it and publish a new version.

**Comment by piranna** [comment]
I have check it again with the in-development version after fixing it and can confirm again that @tyomitch changes has fixed my issue :-) Can we merge and publish them?

**Comment by piranna** [comment]
Sorry, didn't see it was merged yesterday. Can we publish it to npm so we can close this issue? And what we do with the pull-request with the faling test? Should we merge it too?

**Comment by kpdecker** [comment]
My plan is to release a version early this week. Want to try to get all
outstanding PRs in first.

**Comment by tyomitch** [comment]
> And what we do with the pull-request with the faling test? Should we merge it too?

#192 included your test case.

**Comment by piranna** [comment]
> My plan is to release a version early this week. Want to try to get all
> outstanding PRs in first.

That would be cool, thanks :-)

**Comment by piranna** [comment]
Since this is already fixed on master, can it be published a new version on npm? I have several packages broken and development stopped due to this dependency...

**Comment by kpdecker** [comment]
Released in v3.3.1

**Comment by piranna** [comment]
Thank you :-)
