### ISSUE TITLE
long long time to diff escaped string

### ISSUE THREAD

**Issue by daisy-cyt** [kpdecker/jsdiff#202]
I made a mistake that I forget unescape one of the two texts,
so text 1 is escaped like this(only part of true text):
%u5FB7%u56FD%u767E%u5E74%u53A8%u5177%u5EB7%u5DF4%u8D6B%u5B98%u65B9%u65D7%u8230%u5E97

text 2 is unescaped like this(only part of true text):
德国百年厨具康巴赫官方旗舰店

Then I found that it took a long time to compare two texts, I don't konw why. Is it caused by escaped?

**Comment by ExplodingCabbage** [comment]
The time taken to compute a diff is `O((N+M)D)` where N and M are the lengths of the strings being diffed and D is the edit distance between them (i.e. the number of edits needed to transform one into the other). If one string is escaped and the other is not, then they're presumably almost entirely different strings, so D will be large (roughly equal to N+M, in fact).

I've merged some performance improvements to master recently and have no doubt that substantial further improvement is possible, but fundamentally it is expected that any optimal diffing algorithm will be slow when diffing large strings that are completely different from each other.
