### ISSUE TITLE
createPatch adds new line in one-line oldStr

### ISSUE THREAD

**Issue by damirm** [kpdecker/jsdiff#209]
Is it expected behaviour?
```
> diff.applyPatch('', diff.createPatch('test', '', 'a'))
'a\n'
```

Generated patch looks like:
```
> console.log(diff.createPatch('test', '', 'a'))
Index: test
===================================================================
--- test
+++ test
@@ -1,0 +1,1 @@
\ No newline at end of file
+a

```
(with new line at the end)

Why createPatch added new line at the end?
I didn't found test case for one line patches, without `\n` in oldStr and newStr.

**Comment by damirm** [comment]
For example patch generated via `diff` utility:

```
$ cat a

$ cat b
a
$ diff -u a b
--- a	2018-02-03 13:59:41.000000000 +0300
+++ b	2018-02-03 13:59:45.000000000 +0300
@@ -1 +1 @@
-
+a
```

There is no new line at the end.

**Comment by ExplodingCabbage** [comment]
I'm not sure when, but this seems to have been fixed at some point. I see this on master:

```
> diff.applyPatch('', diff.createPatch('test', '', 'a'))
'a'
```
