### ISSUE TITLE
What is `count` in a change object?

### ISSUE THREAD

**Issue by rococode** [kpdecker/jsdiff#210]
![](https://i.imgur.com/F4sK05k.png)

What do those counts mean? Unless I'm missing something it doesn't seem to be mentioned in the spec at all. In the image above I'm using word diff.

Edit: Oh, it seems it's a count of the type that was diffed? So in this case it's a count of "words" (except spaces are counted too) and for a `diffChars` it counts characters. What's a potential use case for that info?

**Comment by unional** [comment]
Would like to know too. It does not seem to reflect the number of lines when doing line diff.

**Comment by Dzenly** [comment]
I also trying to analyze it. It seems that 'count' is the tokens count.

Tokens can be such as:
* word
* whitespaces groups
* punctuation signs
* etc.

E.g. for `diffWordsWithSpace` you can set breakpoint to 

`node_modules/diff/lib/diff/base.js:38`

on the string:
```
var newLen = newString.length,
```
and see `newString` content, it keeps tokens.

**Comment by ExplodingCabbage** [comment]
> What's a potential use case for that info?

You can add the numbers of added/removed tokens up to show summary stats like GitHub does on pull requests:

![image](https://github.com/kpdecker/jsdiff/assets/2358339/e3ebd136-7afb-4b78-84e0-0cd61bfb8f0c)

It's also useful for understanding how the underlying algorithm works (in particular how it is tokenizing stuff), especially if you're getting results that intuitively seem like a sub-optimal diff! For instance, in the issue description you figured out from these numbers that `diffWords` treats spaces between words as tokens (something which I think is kinda broken behaviour, tbh, with [bad consequences beyond the count values](https://github.com/kpdecker/jsdiff/issues/160#issuecomment-1866099640)).

I can also imagine hypothetical uses like showing in some kind of review tool that the user has so far reviewed (or scrolled past) x% of all inserted content and y% of all deleted content, though I've not seen an example of such functionality in the wild.

**Comment by ExplodingCabbage** [comment]
Anyway, you're right that the docs don't mention this, and that seems bad. We should document `count`. I'll probably do this and https://github.com/kpdecker/jsdiff/issues/149 in one swoop since *both* of these issues depend upon documenting a more fundamental point: that each diffing function exposed by the library has its own way of splitting the input into "tokens" and that the core diffing algorithm then acts on the series of tokens. It probably makes sense to write up all of that in one go.

**Comment by ExplodingCabbage** [comment]
By the way, @rococode, I'd love any feedback you have on the updates to the README I've made to address this. :)
