### ISSUE TITLE
Issue with using with rollup

### ISSUE THREAD

**Issue by SumNeuron** [kpdecker/jsdiff#223]
I am trying to use jsdiff with rollup. 

Following the instructions for npm, I successfully installed it. 

Then in my code I have:

`import {createPatch} from 'diff';`

with  error

Error: 'createPatch' is not exported by node_modules/diff/dist/diff.js

**Comment by ExplodingCabbage** [comment]
Can't repro; if I init a new npm package with `"type": "module"` in its `package.json` and run `npm install diff` and then write a .js file inside that package that just says `import {createPatch} from 'diff';` and run `node bla.js`, it works fine and doesn't repro this error.

Happy to take another look if you can provide full instructions on how to reproduce the error.
