### ISSUE TITLE
How to determine equality?

### ISSUE THREAD

**Issue by ithinkihaveacat** [kpdecker/jsdiff#226]
I feel like I must be missing something, but what's the best way to determine if `oldObj` and `newObj` are actually equal? If there's exactly one change object?

**Comment by draperunner** [comment]
Maybe checking `length === 1` is good enough, but I'm doing this:
```
const hasStructuralChanges = diffJson(oldObj, newObj)
        .filter(change => change.added || change.removed)
        .length > 0
```

**Comment by ExplodingCabbage** [comment]
`length === 1` could also mean that one of the strings/sequences was empty and that the diff represents the creation or deletion of the entire text. Checking that none of the change objects have `.added` or `.removed` seems like the right way!
