### ISSUE TITLE
analyze differences based on word boundaries

### ISSUE THREAD

**Issue by yyz1989** [kpdecker/jsdiff#230]
Hi,

I don't know how to name this situation, but let me show two examples to explain. Please see the screenshots attached, where the green part is the inserted part.

<img width="176" alt="screen shot 2018-09-09 at 09 27 16" src="https://user-images.githubusercontent.com/7029943/45262192-9b236800-b412-11e8-9274-c24564ef0dea.png">

```
old: become:[nsubj]
new: become:[nmod:in, nsubj]
```

Ideally I would like to highlight "nmod:in, ", but it seems to try to reuse the existing letters as much as possible.

<img width="198" alt="screen shot 2018-09-09 at 09 26 04" src="https://user-images.githubusercontent.com/7029943/45262193-9bbbfe80-b412-11e8-9e5b-dbf22308c2d2.png">

```
old: become:[xcomp]
new: become:[x_acl:relcl, xcomp]
```

I also prefer to have "x_acl:relcl, " as difference, but now it is also split into two parts...

The function I used is `diffChars`. is there anything I can do to consider word boundaries? Any hint is highly appreciated.

Best regards,
Yang

**Comment by ExplodingCabbage** [comment]
Sounds like you want `diffWords`? 

![image](https://github.com/kpdecker/jsdiff/assets/2358339/aba99f99-516f-45fd-a9e1-7f9a16172cd7)

(`diffWords` has some issues right now around how it handles spaces but it'll handle your example fine!)

**Comment by ExplodingCabbage** [comment]
(You can play with word vs character diffs at http://incaseofstairs.com/jsdiff/ to see the difference, btw!)
