### ISSUE TITLE
Provide a false value instead of undefined

### ISSUE THREAD

**Issue by giorgio79** [kpdecker/jsdiff#233]
For removed, or added values instead of false an undefined is provided. 

Would be nice to provide false instead of undefined.

```
{ a: 'On the other hand , I love you .',
  b: 'Because , I love you .' }
[ { count: 4,
    added: undefined,
    removed: true,
    value: [ 'On', 'the', 'other', 'hand' ] },
  { count: 1,
    added: true,
    removed: undefined,
    value: [ 'Because' ] },
  { count: 5, value: [ ',', 'I', 'love', 'you', '.' ] } ]

```

**Comment by ExplodingCabbage** [comment]
I think I agree. Especially for TypeScript users (currently using the third-party type definitions from DefinitelyTyped), it'd be nice to have consistent types and not have to puzzle over whether there's a semantic distinction between `removed: false` and `removed: undefined`. The single downside I see to this change is that it'll mean serializing a patch object to JSON with `JSON.stringify` (which simply omits properties whose value is `undefined`) will produce slightly larger objects, potentially harming performance for  anyone who's using jsdiff serverside and emitting diffs to a client as JSON. For that reason I think it makes sense to do this but treat it as a breaking change.
