### ISSUE TITLE
`diffWords` is not ignoring white space

### ISSUE THREAD

**Issue by klister10** [kpdecker/jsdiff#236]
I am using `diffWords` to compare two strings, but I am having a problem. Whitespace is being included in the diff, even though I am not using `diffWordsWithSpace`. I tried switching to `diffWordsWithSpace` just to verify, and the behavior remained exactly the same

**Comment by ThomasArdal** [comment]
Is it possible to fix this somehow or is there a workaround? Just experienced the same problem.

**Comment by damien-monni** [comment]
Same problem for me

**Comment by varunmankal** [comment]
I am facing the same problem too.

**Comment by ExplodingCabbage** [comment]
Agree that this is a total mess right now. I'm gonna close this as a duplicate of https://github.com/kpdecker/jsdiff/issues/436, though, where I've got some examples of the brokenness.
