### ISSUE TITLE
Massive performance degradation when truncating large file (20,000x slower than Google's `diff-match-patch` package)

### ISSUE THREAD

**Issue by josephrocca** [kpdecker/jsdiff#239]
Hi there, I've been having some performance problems with `createPatch` and have managed to create a minimal example that replicates the problem. The patch creation takes about 20,000 times longer than it should. It seems to occur when I'm doing large truncations. [Here's the code](https://glitch.com/edit/#!/js-diff-performance-problems):

```javascript
const {performance} = require("perf_hooks");
const JsDiff = require('diff');
const diff_match_patch = require("diff-match-patch");
const dmp = new diff_match_patch();

function makePatch(oldText, newText) {
  let t;

  t = performance.now();
  let textPatch1 = JsDiff.createPatch("foo.txt", oldText+"\n", newText+"\n", "", "");
  console.log("JsDiff (ms):", performance.now()-t);

  t = performance.now();
  let textPatch2 = dmp.patch_make(oldText+"\n", newText+"\n");
  console.log("diff_patch_match (ms):", performance.now()-t);
}

// make a string of 25k lines of random numbers:
text1 = new Array(25000).fill(0).map(n => new Array(20).fill(1).map(n => Math.floor(Math.random()*10)).join("")).join("\n");
// grab the first 10,000 characters:
text2 = text1.slice(0, 10000);
// make the patch:
makePatch(text1, text2);
```

Here's the output I get for that:
```
JsDiff (ms): 133238.9396559
diff_patch_match (ms): 6.825272083282471
```
So unless I'm doing something wrong here, there's a huge performance disparity between this package and the `diff-patch-match` package for patch creation in certain situations. `diff-patch-match` is normally about 2x-10x faster depending on the size of the strings, but here its *a lot* faster... so something's obviously going wrong here.

This is what I'm seeing in the profiler:

![image](https://user-images.githubusercontent.com/1167575/50503885-0e361480-0abe-11e9-86c3-572777b6824c.png)

Any idea what's happening here?

**Comment by leoswing** [comment]
> Hi there, I've been having some performance problems with `createPatch` and have managed to create a minimal example that replicates the problem. The patch creation takes about 20,000 times longer than it should. It seems to occur when I'm doing large truncations. [Here's the code](https://glitch.com/edit/#!/js-diff-performance-problems):
> 
> ```js
> const {performance} = require("perf_hooks");
> const JsDiff = require('diff');
> const diff_match_patch = require("diff-match-patch");
> const dmp = new diff_match_patch();
> 
> function makePatch(oldText, newText) {
>   let t;
> 
>   t = performance.now();
>   let textPatch1 = JsDiff.createPatch("foo.txt", oldText+"\n", newText+"\n", "", "");
>   console.log("JsDiff (ms):", performance.now()-t);
> 
>   t = performance.now();
>   let textPatch2 = dmp.patch_make(oldText+"\n", newText+"\n");
>   console.log("diff_patch_match (ms):", performance.now()-t);
> }
> 
> // make a string of 25k lines of random numbers:
> text1 = new Array(25000).fill(0).map(n => new Array(20).fill(1).map(n => Math.floor(Math.random()*10)).join("")).join("\n");
> // grab the first 10,000 characters:
> text2 = text1.slice(0, 10000);
> // make the patch:
> makePatch(text1, text2);
> ```
> 
> Here's the output I get for that:
> 
> ```
> JsDiff (ms): 133238.9396559
> diff_patch_match (ms): 6.825272083282471
> ```
> 
> So unless I'm doing something wrong here, there's a huge performance disparity between this package and the `diff-patch-match` package for patch creation in certain situations. `diff-patch-match` is normally about 2x-10x faster depending on the size of the strings, but here its _a lot_ faster... so something's obviously going wrong here.
> 
> This is what I'm seeing in the profiler:
> 
> ![image](https://user-images.githubusercontent.com/1167575/50503885-0e361480-0abe-11e9-86c3-572777b6824c.png)
> 
> Any idea what's happening here?

But google diff could not generate a diff like git diff or linux diff tool, so it could not make a beautiful diff, any solutions? Much appriciated

**Comment by joyceerhl** [comment]
I profiled `createPatch` from v5.0.0 of this library after running into this exact issue and wondering why Google's DMP implementation is so much more performant. For my inputs of ~34K LOC, over 50% of the execution time is spent garbage collecting JS objects when I inline the function definition of `clonePath` here:
https://github.com/kpdecker/jsdiff/blob/d358a573dc38fb89dd5ee296805e29f75c932a58/src/diff/base.js#L66
https://github.com/kpdecker/jsdiff/blob/d358a573dc38fb89dd5ee296805e29f75c932a58/src/diff/base.js#L230-L232
![image](https://user-images.githubusercontent.com/30305945/146096220-ca4ffdbb-6edf-4832-91de-e85e17ae22a5.png)

**Comment by erothmayer** [comment]
I ran into this as well. There are a few spots which are using new objects inefficiently, with `clonePath` being the worst among them. The current algorithm does a shallow-clone of the entire diagonal every time it takes a step forward, which ends up churning memory really badly on large files. I was unable to diff 2 ~10k LOC files at all, the browser just hangs.

I have a working copy of a local change which makes this a lot better, which I'll PR shortly.

**Comment by ExplodingCabbage** [comment]
https://github.com/kpdecker/jsdiff/pull/448 and https://github.com/kpdecker/jsdiff/pull/411 have sped jsdiff up on this example to the point that it can generate the patch almost instantly now - about 15-30ms on my machine.

**Comment by ExplodingCabbage** [comment]
(Note they're pre-release, but you can test against master if you want to confirm.)
