### ISSUE TITLE
index.cjs.js not built on package manager install

### ISSUE THREAD

**Issue by julianlam** [kpdecker/jsdiff#242]
Our automated build failed on upgrade to latest `diff`: https://github.com/NodeBB/NodeBB/pull/7198

Looks like the [main file referenced in `package.json`](https://github.com/kpdecker/jsdiff/blob/master/package.json#L24) isn't built on package manager install (at least, not by yarn on my local machine, and npm on Travis CI).

Casual inspection of the lib folder shows `index.es6.js`, but not `index.cjs.js`.

Thanks.

**Comment by kpdecker** [comment]
Should be fixed in 4.0.1

**Comment by julianlam** [comment]
@kpdecker That was fast, thank you very much :smile:
