### ISSUE TITLE
How to build the project into one bundled file from this source code?

### ISSUE THREAD

**Issue by DvirH** [kpdecker/jsdiff#252]

**Comment by ridespirals** [comment]
What do you need it in a single file for? if you want to use this in a web app, you'll need to use something like browserify or webpack to create a bundle.

**Comment by ExplodingCabbage** [comment]
Run `yarn grunt`, then take `dist/diff.js`. Alternatively get it from the `dist/` folder in the "Code" tab at https://www.npmjs.com/package/diff.
