### ISSUE TITLE
WordDiff: Leading and trailing whitespace unnecessarily included in added/removed chunks

### ISSUE THREAD

**Issue by papandreou** [kpdecker/jsdiff#253]
Currently this holds true:

```js
const diffResult = diffWords('foo bar quux baz', 'foo quux bar baz');
expect(convertChangesToXML(diffResult)).to.equal('foo <ins>quux </ins>bar <del>quux </del>baz');
```

The fact that the trailing whitespace is included in the added/removed chunks instead of being left as part of the unchanged ones makes for a funny-looking rendered diff:

![foobarquuxbaz](https://user-images.githubusercontent.com/373545/56622271-a472e500-662f-11e9-8268-5920ec697822.png)

It would be nice if it came out as `foo <ins>quux</ins> bar <del>quux</del> baz` instead, would that be possible to achieve?

**Comment by EfraMarin** [comment]
I can't find the **diff.js** file I just downloaded the project as zip. Is it included in some part in the project?

**Comment by papandreou** [comment]
Sorry, I think I was sleep-deprived when I opened this issue. The current behavior makes sense for the case I quoted, and the weirdness must come from something I'm doing in my end.
