### ISSUE TITLE
Have a problem with "createTwoFilesPatch" method

### ISSUE THREAD

**Issue by lwf804** [kpdecker/jsdiff#254]
I use jsdiff with diff2html to show diff of two strings.
Here: https://codepen.io/lwf804/pen/KYOxBL?editors=1001
![image](https://user-images.githubusercontent.com/42629663/57119650-1bc61880-6d96-11e9-8c5d-25f7178e3d26.png)

I don't know why line one is changed. Can you explain for me?
Thanks!

**Comment by antonin-lebrard** [comment]
Its because there is a newline character at the end of the stringTwo:
```
var stringOne = "string 1",
      stringTwo = `string 1 // <= here there is a \n character that the stringOne doesn't have

b`
```

**Comment by ExplodingCabbage** [comment]
Correct. This matches the behaviour of the `diff` Unix util.

**Comment by ExplodingCabbage** [comment]
(You can preprocess your strings to ensure they always end with a trailing newline if you don't like this behaviour.)
