### ISSUE TITLE
Is this MIT license ?

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [kpdecker/jsdiff#265]
I wanted to use this in my enterprise application. 
Can I use it ? or any licensing issue will be there

**Comment by Neeraj-swarnkar** [comment]
Here I am looking for few details -

Can I use this library in my enterprise company project ? any license ? https://github.com/kpdecker/jsdiff/blob/master/LICENSE

Can i assume this is stable component we can refer and use in project.

Thanks for awesome library and work, looking forward to hear from you. Thanks.

**Comment by not-a-seagull** [comment]
I think the author is inactive. In either case, this looks like BSD 3-clause to me (which I _think_ is compatible with MIT)

**Comment by kpdecker** [comment]
Yes it's BSD. This is a question for your legal department, but this license is intentionally permissive.
