### ISSUE TITLE
Change object contains extra unwanted items

### ISSUE THREAD

**Issue by jpgklassen** [kpdecker/jsdiff#271]
I expected the change object to contain only the changes between `oldStr` and `newStr`. However, it also contains extra items with `value` and `count` fields but no `added` or `removed` fields.

What are these extra items for? Are they really necessary? It would be nice if there was a simple way to determine the number of changes between `oldStr` and `newStr`, eg:

```
let diff = diffLines(oldStr, newStr)
console.log("Number of changes: " + diff.length)
```

Also, it would be nice to be able to iterate through all the changes easily, like so:

```
for (let i=0; i<diff.length; i++) {
  console.log(diff[i].value)
}
```

But instead, we have to manually filter out all the extra items that are not changes. This seems unintuitive to me!

**Comment by leviwheatcroft** [comment]
I disagree.

The unchanged lines may be unwanted in your specific use case, but it's much easier to remove them from the diffLines result if you don't need them, than it would be to identify unchanged lines if you did need them.

Including unchanged lines allows both oldFile and newFile to be derived from the result.

In practical terms, suppose you wanted to render a file showing which lines have been added and which have been removed. If difflines only included the changes then you'd need to iterate over the lines in the original file, while checking your diffLines result to see if a line has changed. Seems cumbersome.

filtering out the stuff you don't need is a snap:

```
diffLines(old, new)
  .filter({ added, removed } => added || removed)
  .forEach({ value } => console.log(value))
```

**Comment by ExplodingCabbage** [comment]
> If difflines only included the changes then you'd need to iterate over the lines in the original file, while checking your diffLines result to see if a line has changed. Seems cumbersome.

It's worse than cumbersome; I don't think it's even possible. jsdiff's change objects don't include line numbers, so, given an insertion or deletion in the list of change objects, how would you even know where to apply it if you don't have the conserved sections in the array of change objects?

Fundamentally, for it to be possible to apply a diff, there has to be *some* kind of indication of where to apply each insertion or deletion. The unified diff format indicates this using line numbers and a limited number of surrounding context lines; jsdiff indicates it by including the entirety of the common/conserved content in the change objects it returns. If we were to stop doing that, we'd need to replace it with *something* else (e.g. including line / word / character / token offsets in the change objects) or else the change objects would be meaningless.

No doubt different ways of indicating insertion and deletion locations all have their own merits and there's a case to be made that doing so with offsets is better than doing so the way jsdiff does, but regardless, any change to this would be a major backwards compatibility break and wouldn't give us a *significantly* better interface (and arguably wouldn't be an improvement at all). Anyone who prefers a different format for their results can write a wrapper of a few lines to convert what jsdiff returns to whatever they'd like. I say we leave this aspect of the API alone.
