### ISSUE TITLE
between windows text(CRLF) and Mac/Linux(LF) text.

### ISSUE THREAD

**Issue by cctakaso** [kpdecker/jsdiff#275]
We find to a problem at diff between windows text(CRLF) and Mac/Linux(LF) text.
ex)
widnows text file
1. abc(CRLF)
2. def
------------
mac text file
1. abc(LF)
2. def

Now, this answer is as follow.
first line  is different !

line.js
7     linesAndNewlines = value.split(/(\n|\r\n)/);
-->
this is may must be ....
7     linesAndNewlines = value.split(/(\r\n|\n)/);

thanks for your support!

**Comment by ExplodingCabbage** [comment]
Resolved by https://github.com/kpdecker/jsdiff/pull/344
