### ISSUE TITLE
What does count mean in change object

### ISSUE THREAD

**Issue by dawoodaijaz97** [kpdecker/jsdiff#277]
{ count: 27,
    added: true,
    removed: undefined,
    value:
     'is an American multinational technology company that specializes in Internet-related services and products' },
  { count: 2, value: ', ' },
I get the following change object can anyone explain this to me
what does count actually mean

**Comment by UziTech** [comment]
I believe count is the number of items in the `value`.
For `diffWords` it is the number of words or non word characters (i.e. '` `', '`,`', '`-`')

**Comment by kudlav** [comment]
Duplicate of https://github.com/kpdecker/jsdiff/issues/210
