### ISSUE TITLE
How to show Number of Diff(s)

### ISSUE THREAD

**Issue by saralproject** [kpdecker/jsdiff#289]
Thanks for great data. but i want to know how to show nuber of difference in in result. for example
amit is a good boy [test1]
sumit is not a good boy. [test2]
output .............. and diffrence : 3

**Comment by ygj6** [comment]
@saralproject 
The following example meets your expectations?

**Code：**
```
    const jsDiff = require('diff')

    const one = "amit is a good boy [test1]"
    const other = "sumit is not a good boy. [test2]"

    const diff = jsDiff.diffWords(one, other)

    let Num =0

    diff.forEach((part) => {
        console.log(part)
        if(part.added) Num ++
    })
    console.log("diffrence:", Num)
```
**Output：**
```
{ count: 1, added: undefined, removed: true, value: 'amit' }
{ count: 1, added: true, removed: undefined, value: 'sumit' }
{ count: 3, value: ' is ' }
{ count: 2, added: true, removed: undefined, value: 'not ' }
{ count: 5, value: 'a good boy' }
{ count: 1, added: true, removed: undefined, value: '.' }
{ count: 2, value: ' [' }
{ count: 1, added: undefined, removed: true, value: 'test1' }
{ count: 1, added: true, removed: undefined, value: 'test2' }
{ count: 1, value: ']' }
diffrence: 4
```

**Comment by madoBaker** [comment]
Building on the previous response, you can also use the filter function to get the total number of differences

`   const jsDiff = require('diff')

    const one = "amit is a good boy [test1]"
    const other = "sumit is not a good boy. [test2]"

    const diff = jsDiff.diffWords(one, other)

   const differences = diff.filter(d => d.added || d.removed).length;
`
