### ISSUE TITLE
Native ESM

### ISSUE THREAD

**Issue by lukeed** [kpdecker/jsdiff#292]
Hey there, trying to add support native ESM within `uvu`, and `diff` is the only blocker. 

You have `main/module` setup, but in Node versions that support ESM, they're picking up the CommonJS/`
main"` build, which nests everything behind a `default` key.

To fix this, all you need to do is add this to your `package.json` file:

```js
"export": {
  ".": {
    "import": "./lib/index.mjs",
    "require": "./lib/index.js"
  },
  "./package.json": "./package.json"
}
```

And then kick out an extra `lib/index.mjs` file with the same contents as `lib/index.es6.js`.

Check [this repo](https://github.com/TehShrike/uvu-diff-repro) for a simple reproduction. 
It has nothing to do with `uvu` by the way, it's just how I uncovered the problem.

**Comment by kpdecker** [comment]
Glad to take a PR on this.

- Kevin Decker
kpdecker@gmail.com
