### ISSUE TITLE
Using this library for an undo stack

### ISSUE THREAD

**Issue by ericbiewener** [kpdecker/jsdiff#298]
I'm considering using this library to maintain an undo stack. My plan is:

1. Serialize the state I want to make un-doable
2. use `createPatch()` to generate the diff between the new state and old
3. use `applyPatch` and deserialize the result to perform the undo action

I'm concerned that this library has not been developed with this use case in mind because `createPatch()` doesn't allow me to specify the number of "context" lines to include around the actual patch lines. For my use case, I don't want any context lines since I ultimately want to keep the memory footprint as minimal as possible.

Is there a part of the API that I'm missing? Or would you recommend a different library to accomplish this? I considered [deep-diff](https://www.npmjs.com/package/deep-diff), but I'm currently more concerned about memory usage than performance, and [the benchmarking I've done](https://www.measurethat.net/Benchmarks/Show/9657/1/js-diff-vs-deep-diff---diff-creation) indicates that the patch diffs generated by this library will be smaller.

**Comment by ExplodingCabbage** [comment]
> `createPatch()` doesn't allow me to specify the number of "context" lines to include around the actual patch lines

Not so; you can specify this with the `context` option:

```
> text1 = 'line1\nline2\nline3\nline4\nline5\nline6\nline7\nline8\nline9\nline10\n'
'line1\nline2\nline3\nline4\nline5\nline6\nline7\nline8\nline9\nline10\n'
> text2 = 'line1\nline2\nline3\nline4\nline5\nlineXXX\nline7\nline8\nline9\nline10\n'
'line1\nline2\nline3\nline4\nline5\nlineXXX\nline7\nline8\nline9\nline10\n'
> diff.createPatch('myfile.txt', text1, text2)
'Index: myfile.txt\n' +
  '===================================================================\n' +
  '--- myfile.txt\n' +
  '+++ myfile.txt\n' +
  '@@ -2,9 +2,9 @@\n' +
  ' line2\n' +
  ' line3\n' +
  ' line4\n' +
  ' line5\n' +
  '-line6\n' +
  '+lineXXX\n' +
  ' line7\n' +
  ' line8\n' +
  ' line9\n' +
  ' line10\n'
> diff.createPatch('myfile.txt', text1, text2, undefined, undefined, {context: 2})
'Index: myfile.txt\n' +
  '===================================================================\n' +
  '--- myfile.txt\n' +
  '+++ myfile.txt\n' +
  '@@ -4,5 +4,5 @@\n' +
  ' line4\n' +
  ' line5\n' +
  '-line6\n' +
  '+lineXXX\n' +
  ' line7\n' +
  ' line8\n'
> diff.createPatch('myfile.txt', text1, text2, undefined, undefined, {context: 10})
'Index: myfile.txt\n' +
  '===================================================================\n' +
  '--- myfile.txt\n' +
  '+++ myfile.txt\n' +
  '@@ -1,10 +1,10 @@\n' +
  ' line1\n' +
  ' line2\n' +
  ' line3\n' +
  ' line4\n' +
  ' line5\n' +
  '-line6\n' +
  '+lineXXX\n' +
  ' line7\n' +
  ' line8\n' +
  ' line9\n' +
  ' line10\n'
```

**Comment by ExplodingCabbage** [comment]
For completeness I should note that `context: 0` works too!

```
> diff.createPatch('myfile.txt', text1, text2, undefined, undefined, {context: 0})
'Index: myfile.txt\n' +
  '===================================================================\n' +
  '--- myfile.txt\n' +
  '+++ myfile.txt\n' +
  '@@ -6,1 +6,1 @@\n' +
  '-line6\n' +
  '+lineXXX\n'
```
