### ISSUE TITLE
How to/Can we open the difference result in HTML page for NodeJS?

### ISSUE THREAD

**Issue by guptapranay** [kpdecker/jsdiff#301]
I am trying to use this node module in my NodeJS framework. Trying to compare two JSON files.

I wish to show the result generated in the HTML file.  Is it possible to do it?

**Comment by ExplodingCabbage** [comment]
Of course. There are examples in the `examples` folder, plus of course the [gh-pages site](https://github.com/kpdecker/jsdiff/tree/gh-pages).
