### ISSUE TITLE
Please adapt to newer mocha versions

### ISSUE THREAD

**Issue by SnarkBoojum** [kpdecker/jsdiff#302]
Newer mocha releases complain with a warning ; soon they'll just error out:
```
DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
```

Thanks

**Comment by ExplodingCabbage** [comment]
In what context do you see this warning? I don't see it if I run `yarn test`. (It might be nice to upgrade the dev dependencies anyway, of course.)

**Comment by ExplodingCabbage** [comment]
I'm still not sure what *this issue* is about, though (I can't repro the error message mentioned in it, nor do I understand how anything could "soon" change unless jsdiff explicitly upgrades the version of Mocha it depends on in its `yarn.lock`, nor do I see any sign that we're using `mocha.opts` anywhere), so I'm gonna close it for now pending more explanation.
