### ISSUE TITLE
Not able to run the HTML Web page example.

### ISSUE THREAD

**Issue by Aniruddha612** [kpdecker/jsdiff#327]
The steps to build for diff.js file is not provided in the repository. Can you help me regarding building the diff.js file ?

**Comment by dragosiancu0504** [comment]
Hello! Try installing the node package running "npm install diff --save".
Then in the node modules, find the "diff" folder which contains the diff.js file you are searching for.
Hope this helps, cheers!

**Comment by ozturkib** [comment]
I experienced the same issue and the solution is [here](https://github.com/kpdecker/jsdiff/issues/362#issuecomment-1543625050). Thanks
