### ISSUE TITLE
Full online demo link broken

### ISSUE THREAD

**Issue by commodis** [kpdecker/jsdiff#334]
I was trying the `full online demo` in the [README](https://github.com/kpdecker/jsdiff/blob/d358a573dc38fb89dd5ee296805e29f75c932a58/README.md?plain=1#L198) which links to https://kpdecker.github.com/jsdiff. But this page is reported as `Page not found`.

Where is the full online demo?

**Comment by mh166** [comment]
As per GitHub's error message, you can substitute `.com` in that URL for `.io` to get to the desired location. So https://kpdecker.github.io/jsdiff it is for the actual demo site. 😊

**Comment by waldyrious** [comment]
For the record, there's an open PR to fix this: #321.
