### ISSUE TITLE
Handling merge conflicts

### ISSUE THREAD

**Issue by AlonBru** [kpdecker/jsdiff#335]
Been trying to use this library for a text editor where when you save it checks for conflicts between your version, the server version and the version you started with.
If there are conflicts I display a ui to resolve these conflicts, but I have yet to figure out if there is an intended way to resolve them, using the information provided by the api.
any help and ideas would be apreciated, thanks!

**Comment by doug65536** [comment]
I managed it by hand parsing the merge result in my code, handling the '+' '-' or space or empty line, and handling the object with a conflict property equal to true.

**Comment by ExplodingCabbage** [comment]
Yeah it's really up to the application what it wants to do with `conflict: true` lines in hunks. You could have an automated rule like keep mine, or keep theirs, or concatenate the insertions when it's an insertion conflict. Or you could add merge markers like Git does on a merge conflict. Or some other kind of UI. jsdiff isn't opinionated about it.

**Comment by ExplodingCabbage** [comment]
Probably worth saying: there are broadly two strategies I see here:

1. apply the patch-with-conflicts to your source file yourself, with your own code which also handles conflicts, or
2. *modify* the patch to eliminate the conflicting lines (e.g. by replacing them with the `mine` or `theirs` version or by replacing them with conflict markers and both alternatives), then apply the *modified* patch with `applyPatch`.

My instinct is that the latter approach is nicer!
