### ISSUE TITLE
diff for large arrays never returns and uses 100% CPU forever

### ISSUE THREAD

**Issue by joniba** [kpdecker/jsdiff#353]
When comparing large arrays (over 350 elments) containing nested JSON objcts, `diffJson` never returns and the process uses 100% CPU forever. Quite a disappointment. I'm guessing this is pretty easy to replicate, but I'm sure I can fabricate an example if needed.

EDIT: Actually I found that I can't easily reproduce this manually. This occurs when comparing objects retrieved from the DB, but doesn't seem to occur with simple fabricated objects, even when they are nested. If I succeed in reproducing I'll post some code.

**Comment by sphawkins** [comment]
I am having the exact same issue. In my case I am serializing data objects to json and comparing them against a prior json object. It appears as though it isn't the number of total elements, but rather the number of changes. In my case I am estimating there are about 1400 changes between these two jsons. When I cut the number in half, it displays quite quickly.

**Comment by ExplodingCabbage** [comment]
There have been a couple of major performance improvements on master (not yet released to npm) that probably resolve this: https://github.com/kpdecker/jsdiff/pull/411, https://github.com/kpdecker/jsdiff/pull/448.
