### ISSUE TITLE
Incorrect return value for structuredPatch method

### ISSUE THREAD

**Issue by TianYu0605** [kpdecker/jsdiff#355]
```ts
const oldStr = '1111\n1111\n3333\n4444'
const newStr = '2222\n3333'
const diffResult: IDiffResult = Diff.structuredPatch('oldFileName', 'newFileName', oldStr, newStr, 'oldHeader', 'newHeader')
console.log(diffResult)
```
<img width="996" alt="image" src="https://user-images.githubusercontent.com/49590847/155269272-3f45e367-0475-419a-9eab-ae3db31ce539.png">
why not ["-1111", "-1111", "+2222", "3333", "-4444"]

3333 is not change

**Comment by ExplodingCabbage** [comment]
I think this is just how unified diff format encodes the information that the line 3333 was terminated with a line feed character in the old string but no longer is in the new string. At least, the GNU `diff` util does the same thing if you ask it to use unified diff format, and I figure that the behaviour of `diff -u` is the closest thing to a standard we've got:

```
mark@fractal:~$ node
Welcome to Node.js v21.1.0.
Type ".help" for more information.
> fs.writeFileSync('x.txt', '1111\n1111\n3333\n4444')
undefined
> fs.writeFileSync('y.txt', '2222\n3333')
undefined
> 
mark@fractal:~$ diff -u x.txt y.txt 
--- x.txt	2024-01-09 19:05:54.932866871 +0000
+++ y.txt	2024-01-09 19:06:12.348186624 +0000
@@ -1,4 +1,2 @@
-1111
-1111
-3333
-4444
\ No newline at end of file
+2222
+3333
\ No newline at end of file
```
