### ISSUE TITLE
Special characters in word is accounted as a separate word

### ISSUE THREAD

**Issue by deyayan** [kpdecker/jsdiff#359]
`const diff = diffWordsWithSpace('abcd efgh ijkl', '@abcd@ efgh ijkl')`

**OUTPUT**

```
​{
    added: true,
    count: 1,
    removed: undefined,
    value: "@"
},
{ 
    count: 1, 
    value: "abcd" 
},
​{
    added: true,
    count: 1,
    removed: undefined,
    value: "@"
},
{ 
    count: 4, 
    value: " efgh ijkl" 
}
```

`const diff = diffWordsWithSpace('abcd efgh ijkl', '1abcd1 efgh ijkl')`

**OUTPUT**

```
​{
    added: undefined,
    count: 1,
    removed: true,
    value: "abcd"
},
​{
    added: true,
    count: 1,
    removed: undefined,
    value: "1abcd1"
},
{ 
    count: 4, 
    value: " efgh ijkl" 
}
```

**Comment by theone3nu** [comment]
Same issue I am also facing it is working differently with special characters like * @

How to fix this any alternative solution.

**Comment by ExplodingCabbage** [comment]
Hmm... this seems like a grey area where it's pretty non-obvious what the correct behaviour is. Should `markrobertamery@gmail.com` be a single word or three? Both are defensible! How about `foo,bar,baz` with no spaces? One word or three?

I'm not convinced we should change anything here. I guess I could make `@` be treated as a word character but then I may well get a bug report from someone whose intuition about the "correct" behaviour here is the opposite of yours, and I don't see any basis to say that you or the hypothetical other person has the more correct perspective. If you're not happy with the default `diffWords` behaviour, perhaps it's a good use case for defining [custom diffing behaviour](https://github.com/kpdecker/jsdiff?tab=readme-ov-file#defining-custom-diffing-behaviors).
