### ISSUE TITLE
Diiff.js File Missing 

### ISSUE THREAD

**Issue by subashappvance** [kpdecker/jsdiff#362]
Im not able to get diff.js file in this repo, can someone help me on this

**Comment by itsvetobaby** [comment]
https://cdn.jsdelivr.net/npm/diff@5.1.0/dist/diff.min.js

**Comment by morf46** [comment]
clone the repo and execute rollup yourself

example:
`.\node_modules\.bin\rollup -c`

or run the build process 

`npm run build:node`

you find the diff.js file under the newly created _./dist_ folder

**Comment by ozturkib** [comment]
I got the same experience once I cloned the repo. Even the smaller example under the `examples\web_example.html `does not work properly. There is not enough description for  this side.

Once I run the build process with:

`npm run build:node`

Then, the `diff.js` file comes under the newly created `dist `folder in the root directory (`/dist/`). After this step, the tiny example under the `examples\web_example.html` works properly.

Then, I would like to try the demo in _index.html_ as an HTML web page example; However, it can not show the comparison output on the right hand side.  However, the smaller example under the `examples\web_example.html `works properly. Hence, I realized that the global object of `JsDiff` is modified to `Diff` as below:

```
function changed() {
	if(window.diffType == 'applyPatch') {
		//b.textContent = JsDiff.applyPatch(a.textContent, result.textContent);
		b.textContent = Diff.applyPatch(a.textContent, result.textContent);
	} else if(window.diffType == 'createPatch') {
		//result.textContent = JsDiff.createPatch('filename',a.textContent, b.textContent,'left','right');
		result.textContent = Diff.createPatch('filename',a.textContent, b.textContent,'left','right');
	} else {
		//var diff = JsDiff[window.diffType](a.textContent, b.textContent);
		var diff = Diff[window.diffType](a.textContent, b.textContent);
...
```

Then, everything works fine!
