### ISSUE TITLE
diffLines never returning

### ISSUE THREAD

**Issue by maziac** [kpdecker/jsdiff#376]
Hi,

there seems to be a problem with big files/diffences.
I have here 2 files that differ very much.
1 file is 1 line only the other file is about 13000 lines.

In that case diffLines never returns.

I attached a project to reproduce.
textC is the long text.
If instead of textC the short textB is used everything works fine, but with textB diffLines never exits.

[jsdiffproblem.zip](https://github.com/kpdecker/jsdiff/files/8933868/jsdiffproblem.zip)

**Comment by ExplodingCabbage** [comment]
This takes a fraction of a second now, probably due to https://github.com/kpdecker/jsdiff/pull/448.
