### ISSUE TITLE
diffLines adding extra addition/removal

### ISSUE THREAD

**Issue by okbytes** [kpdecker/jsdiff#382]
I have a string where a line is added to the end. When I run `diffLines` comparing the new and the old strings, `diffLines` puts in an extra addition/removal to the diff. Since the line in question is unchanged, I would expect it to not be included in the addition/removal count.

```js
const old = "SELECT *\nFROM billing"
const new = "SELECT *\nFROM billing\nAS billing"

diffLines(old, new)

diff = [
  {count: 1, value: 'SELECT *\n'},
  {count: 1, added: undefined, removed: true, value: 'FROM billing'},
  {count: 2, added: true, removed: undefined, value: 'FROM billing\nAS billing'}
]
```
<img width="279" alt="image" src="https://user-images.githubusercontent.com/6867344/186745201-75ad97a9-9b0a-43d5-bae8-243b9e69a79a.png">

I would expect this output reflecting a single addition:
```js
diff = [
  {count: 2, value: 'SELECT *\nFROM billing'},
  {count: 1, added: true, removed: undefined, value: 'AS billing'}
]
```

**Comment by benatkin** [comment]
Might need a wrapper to convert the to [POSIX](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795) lines [lines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)

At first blush this makes it seem buggy but if it doesn't get tripped up on files ending in `"\n"` it's workable.
