### ISSUE TITLE
Line diff apply giving extra line in the end when source is empty string

### ISSUE THREAD

**Issue by prabhat-awasthi-3697** [kpdecker/jsdiff#387]
**Case 1: When extra \n is added by appyPatch**

source : "" and destination: "abcd" 

above combination will create the patch as --> "@@ -1,0 +1,1 @@\n+abcd\n"

applyPatch("", ["@@ -1,0 +1,1 @@\n+abcd\n"]) results in --> "abcd\n" (This extra \n is added)

**Case 2: When \n is removed by applyPatch**

source: "" and destination: "abcd\n"

above combination will still result in patch -->  "@@ -1,0 +1,1 @@\n+abcd\n"

**Comment by kartikjain26** [comment]
Facing similar issue related to this.
Extra new line character is added on patching anything to empty string.

**Comment by benatkin** [comment]
Apparently it assumes POSIX lines https://stackoverflow.com/a/729795 and if it isn't comparing one set of lines to another it fails. I would be interested to see a bug report where everything involved ends with a newline.

I think UNIX considers an empty file to be text so that's an issue, sure.

**Comment by ExplodingCabbage** [comment]
> source : "" and destination: "abcd"
>
> above combination will create the patch as --> "@@ -1,0 +1,1 @@\n+abcd\n"

I can't repro this:

```
> source = ""
''
> dest = "abcd"
'abcd'
> patch = diff.createPatch('foo.txt', source, dest)
'Index: foo.txt\n' +
  '===================================================================\n' +
  '--- foo.txt\n' +
  '+++ foo.txt\n' +
  '@@ -0,0 +1,1 @@\n' +
  '+abcd\n' +
  '\\ No newline at end of file\n'
```

Applying the patch works fine for me too:

```
> diff.applyPatch(source, patch)
'abcd'
```

**Comment by benatkin** [comment]
@ExplodingCabbage did you try using a file that didn't have a newline at the end? These are very common.

**Comment by ExplodingCabbage** [comment]
@benatkin I used literally the example strings from the question, which don't contain any newlines.

**Comment by benatkin** [comment]
@ExplodingCabbage I see Case 1 but not Case 2.

**Comment by ExplodingCabbage** [comment]
Good point. Can't repro case 2 either, though:

```
> source = ""
''
> dest = "abcd\n"
'abcd\n'
> 
> diff.createPatch('foo.txt', source, dest)
'Index: foo.txt\n' +
  '===================================================================\n' +
  '--- foo.txt\n' +
  '+++ foo.txt\n' +
  '@@ -0,0 +1,1 @@\n' +
  '+abcd\n'
```

**Comment by benatkin** [comment]
Sweet, it might have been fixed.

**Comment by ExplodingCabbage** [comment]
Yeah I guess so. Not sure which commit/PR did it, though!
