### ISSUE TITLE
[question] Is it possible to preserve the whitespace when using `ignoreWhitespace` ? It breaks the formatting

### ISSUE THREAD

**Issue by dgtlmoon** [kpdecker/jsdiff#389]
Hello and thanks!

In my situation, I want to compare by ignoring the whitespace, however the documents format should not be broken

![image](https://user-images.githubusercontent.com/275001/202852600-039c296f-a69b-487b-9d3a-b3fd7f6c96ec.png)

becomes with `ignoreWhitespace:true`

![image](https://user-images.githubusercontent.com/275001/202852619-805ef306-bf69-4c0f-9b92-2f13baaadb55.png)

**Comment by ExplodingCabbage** [comment]
https://github.com/kpdecker/jsdiff/pull/219 will fix this.

**Comment by dgtlmoon** [comment]
thanks for the attention here :)
