### ISSUE TITLE
Expose the "formatPatch" function

### ISSUE THREAD

**Issue by joffreyvillard** [kpdecker/jsdiff#399]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

_Today I used [patch-package](https://github.com/ds300/patch-package) to patch `diff@5.1.0` for the project I'm working on._

I'd like to use the provided `formatPatch` function along with `structuredPatch`, so that to only display a diff if relevant to my application (cannot apply the conditions on a string representation of the diff, sounds pretty hacky and fragile!). 

I think that `formatPatch` should hence be exported, to be used together with `structuredPatch` as I see fit, instead of directly via `createTwoFilesPatch` that simply combines (and is very suitable anyway!)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/diff/dist/diff.js b/node_modules/diff/dist/diff.js
index 7fa3a55..f7b3efd 100644
--- a/node_modules/diff/dist/diff.js
+++ b/node_modules/diff/dist/diff.js
@@ -1618,6 +1618,7 @@ OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   exports.diffTrimmedLines = diffTrimmedLines;
   exports.diffWords = diffWords;
   exports.diffWordsWithSpace = diffWordsWithSpace;
+  exports.formatPatch = formatPatch;
   exports.merge = merge;
   exports.parsePatch = parsePatch;
   exports.structuredPatch = structuredPatch;
```

_This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

**Comment by ExplodingCabbage** [comment]
Done! https://github.com/kpdecker/jsdiff/pull/451

**Comment by joffreyvillard** [comment]
Thank you!

**Comment by martolini** [comment]
Any chance this can make it to npm, too? ❤️

**Comment by ExplodingCabbage** [comment]
Will do in the next few days, @martolini!

**Comment by leonardobsjr** [comment]
It's unfortunate that @type/diff doesn't expose this yet :|

**Comment by ExplodingCabbage** [comment]
@leonardobsjr I'm hoping to do https://github.com/kpdecker/jsdiff/issues/303 soon and have jsdiff take over its own type definitions instead of deferring the provision of them to DefinitelyTyped. I have absolutely no idea how to do this yet - first time! - so any help would be welcome. But if I succeed then the `@typed/diff` package will be deprecated and there'll be full and correct type in `diff` itself.

**Comment by leonardobsjr** [comment]
@ExplodingCabbage Did a super-barebones types inclusion: https://github.com/kpdecker/jsdiff/pull/496
