### ISSUE TITLE
diffWords is not detecting a deleted space at the end of text.

### ISSUE THREAD

**Issue by firststeven** [kpdecker/jsdiff#402]
Any ideas?

Can anyone else reproduce this issue?

V5.0

**Comment by ExplodingCabbage** [comment]
This is expected. If you want to catch whitespace differences, you need `diffWordsWithSpace`. Per the README:

> `Diff.diffWords(oldStr, newStr[, options])` - diffs two blocks of text, comparing word by word, **ignoring whitespace**.
> ...
> `Diff.diffWordsWithSpace(oldStr, newStr[, options])` - diffs two blocks of text, comparing word by word, **treating whitespace as significant**.

(I was surprised to discover it too.)
