### ISSUE TITLE
Can we ignore specific characters like *,\ etc using diffWords ?

### ISSUE THREAD

**Issue by OmkarPh** [kpdecker/jsdiff#403]
I don't want the following to be detected as a diff.
Ignoring the `*` before & after this word should do the trick ig (I don't want to track special characters in my diff anyway)
![image](https://github.com/kpdecker/jsdiff/assets/48476025/f6867cab-dd1e-4010-be39-be5b86a57fc4)

Is there any way to achieve this?
I'm using `diffWords` here btw

**Comment by ExplodingCabbage** [comment]
Not trivial current way, and I don't think I'd want to add it, but https://github.com/kpdecker/jsdiff/issues/221 is a similar request and might give you the results you want here (if/when I implement it).

The one thing you _can_ currently do is [roll your own tokenization and equality-checking logic](https://github.com/kpdecker/jsdiff?tab=readme-ov-file#defining-custom-diffing-behaviors) to get the behaviour you want.
