### ISSUE TITLE
createPatch How to display all information？

### ISSUE THREAD

**Issue by lush-99** [kpdecker/jsdiff#408]
my html is
![image](https://github.com/kpdecker/jsdiff/assets/77112588/f3e7f49c-7210-4c38-9427-a19111ae6c12)
i hope that display all json
but actually is
![image](https://github.com/kpdecker/jsdiff/assets/77112588/4c562611-54c2-4bca-92ae-57d8db39dd33)

**Comment by ExplodingCabbage** [comment]
I'm not *certain* that I understand the question, but you *might* be looking for the `context` option (CTRL-F for `context` in the README).
