### ISSUE TITLE
jsdiff 5.1.0 version

### ISSUE THREAD

**Issue by paultinker** [kpdecker/jsdiff#413]
Hi Kevin, Team,
The latest version of jsdiff is 5.1.0 as indicated on cdnjs and npm:

https://cdnjs.com/libraries/jsdiff
https://www.npmjs.com/package/diff/v/5.1.0

However, in the source on Github, the latest tag shows as 5.0.0

There are no tags or branches, that give an indication of the 5.1.0 version.  Can you please advise as to the build details?  Or in other words, where is the 5.1.0 version of jsdiff sourced?

Thank you - appreciate your time.  Regards -Paul

**Comment by ExplodingCabbage** [comment]
This is the commit that the 5.1.0 build was generated from, I'm pretty sure: https://github.com/kpdecker/jsdiff/commit/f4cc58c57ae355ccf9fcd442a0d8f9497a02b3c1

(It's the last commit to reach master before the 5.1.0 release went out on npm, and looking at the code on npm confirms that it contains the `options.maxEditLength` feature added in that commit.)

I've pushed a tag now to reflect this. Thanks for catching!

(I guess we can infer that @kpdecker modified package.json locally to change the version number to 5.1.0 before uploading the release, but forgot to push the version number change to GitHub. Oops. Oh well!)
