### ISSUE TITLE
invalid-meta jsdiff is missing "main" entry in bower.json

### ISSUE THREAD

**Issue by vasiliy0s** [kpdecker/jsdiff#44]
Please add `bower.json` to latest tag (better in new).

**Comment by vasiliy0s** [comment]
... and bower installation instructions to README, please

**Comment by kpdecker** [comment]
I'm glad to merge in a pull request.

**Comment by ofbriggs** [comment]
Current version appears to have correct main value, added bower instructions with #53

**Comment by kpdecker** [comment]
Closing in favor of #53. Please let me know if there are still concerns.
