### ISSUE TITLE
diffLines doesn't support ignoring whitespace or leading/following spaces?

### ISSUE THREAD

**Issue by JamesGould123** [kpdecker/jsdiff#46]
I feel like I'm missing something, because it seems like such an obvious feature to include, but there doesn't appear to be a version of diffLines that ignores whitespace and/or leading/following spaces.

**Comment by kpdecker** [comment]
No one has reported the need for this yet. Glad to accept a PR if you have such a need!

**Comment by JamesGould123** [comment]
Sure, I'll see when I can get around to it. :smile:

**Comment by kpdecker** [comment]
Fixed by #47
