### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by webchaz** [kpdecker/jsdiff#48]
Is there anyway for this to work with html, by maintaining the original markup or ignoring html tags, so that only the text is updated, but the html remains intact?

**Comment by mattsgarlata** [comment]
I think this may be as simple as the code below.

```
var HtmlDiff = new diff.Diff(true)
HtmlDiff.tokenize = function(value) {
	return removeEmpty(value.split(/(<>[{}:;,]|\s+)/));
}
var diffs = HtmlDiff.diff(revision1, revision2)
```

**Comment by kpdecker** [comment]
@webchaz could you elaborate on what you are looking for?

**Comment by unkw** [comment]
the problem is not solved

**Comment by kpdecker** [comment]
Closing in favor of #71. Moving discussion there.
