### ISSUE TITLE
Update of gh-pages and examples

### ISSUE THREAD

**Issue by jesperronn** [kpdecker/jsdiff#50]
Hi,

I was struggling with a code example in a jsfiddle, and suddently I realized the js file I pulled was 4 years old.

I pulled http://kpdecker.github.io/jsdiff/diff.js, which comes from `gh-pages`: https://github.com/kpdecker/jsdiff/tree/gh-pages

Do you plan updating this?

**Comment by kpdecker** [comment]
Done.

**Comment by jesperronn** [comment]
Awesome, Thanks!

BTW, I think you should add version number in the header of `diff.js`, but that's another story :)
