### ISSUE TITLE
At the end of the compared text, when there is a punctuation mark, something goes wrong

### ISSUE THREAD

**Issue by anniek-bisschop** [kpdecker/jsdiff#515]
You can also see this happening in the demo tool. When you hit the spacebar after the punctuation mark, it will be corrected.

![test](https://github.com/kpdecker/jsdiff/assets/150704797/6a3a4675-9ecb-4e12-9caa-2035171387cd)

After adding space:
![After space](https://github.com/kpdecker/jsdiff/assets/150704797/29f06dec-dd88-45c1-bbea-7315d0762a72)

**Comment by ExplodingCabbage** [comment]
I can't repro this. If I paste `This is a test` and `This is a test?` into the text areas, with no trailing space, then I get exactly the correct result:

![image](https://github.com/kpdecker/jsdiff/assets/2358339/9770425e-788d-439b-aa8a-6aaf4d10bb4d)

To confirm - you're trying this at http://incaseofstairs.com/jsdiff/? Any chance you're using an old version that's in your browser cache, or that a plugin is interfering somehow? Would be interested to hear if using a different browser magically fixes it. (I don't have anything like a complete theory of how exactly either issue would cause this outcome, though.)

I'm gonna close this as no-repro for now but will reopen and take another look if I get more info.
