### ISSUE TITLE
[Bug Issue]: Issue on init on older devices.

### ISSUE THREAD

**Issue by MarketingPip** [kpdecker/jsdiff#545]
On older version devices of ios safari, when using this library a error is thrown regarding a ungrouped regular expression. Not sure if you want this to be left for devs to use babel etc to deal with for support for older devices. But this will break things on CDN usage for older devices.

**Comment by ExplodingCabbage** [comment]
Could you let me know a version of Safari that this happens on and what the error message is? (If you've got the full traceback or know which regex is causing the error that'd be even better.)

**Comment by MarketingPip** [comment]
@ExplodingCabbage - my apologies Mark. Didn't mean to leave you hanging to find this without a nice error or usage etc. Was on mobile when discovered this and just wanted to make sure I did have it documented for later. I will try newest version when possible and see if I find any issues.

**Comment by ExplodingCabbage** [comment]
Thanks!

**Comment by MarketingPip** [comment]
> Thanks!

@ExplodingCabbage - just reporting (opened my app on my pos old iOS device - tho great for testing browser support 😂😩). Pulled from CDN the latest version. And things appear to be working smoothly. Cheers 🍻 

ps; thank you as well for your contributions to this project / society as a whole ✌️
