### ISSUE TITLE
Ignore punctuation as separate tokens while doing word difference.

### ISSUE THREAD

**Issue by aman-kumar-ops** [kpdecker/jsdiff#546]
How can we ignore the punctuation from being created as separate token when using word difference.

**For Example:**

const oldString = '$35,000,000';
const newString = '$55,000,000';

Library Output:

$<del>35</del>55,000,000

Expect Output:
<del>$35,000,000</del>$55,000,000

**Comment by ExplodingCabbage** [comment]
If you specifically want to ignore commas being used as thousands separators in numbers, then using the `intlSegmenter` argument to `diffWords` should do the trick; it considers `55,000,000` to be a single word.
