### ISSUE TITLE
 Incorrect latest version published on NPM

### ISSUE THREAD

**Issue by alan-agius4** [kpdecker/jsdiff#547]
**Description:**

`6.0.0-beta` version of the `diff` package has been published as the latest version on npm. This seems to be a mistake as beta versions are typically not intended to be the latest stable release.

**Details:**

- **Package Name:** `diff`
- **Current Latest Version on npm:** `6.0.0-beta`
- **Expected Latest Version:** Should be the latest stable version, which is typically not a beta release.

**Steps to Reproduce:**

1. Visit the [npm package page for `diff`](https://www.npmjs.com/package/diff?activeTab=versions).
2. Observe that `6.0.0-beta` is listed as the latest version.

**Expected Behavior:**

The latest stable version should be published as the latest version on npm, not a beta release.

**Comment by ExplodingCabbage** [comment]
Resolved by pushing 6.0.0 - and I've learned about tagging releases, for next time!
