### ISSUE TITLE
The demo is broken with diff lines

### ISSUE THREAD

**Issue by mostafaeweda** [kpdecker/jsdiff#55]
After writing a simple one-word-each 2 lines to both editors and removing them, no matter what I do to make the 2 editors in sync - seems like the diff is saving some bad cache state, where it shouldn't.

The diff should be calculated every time any of the editors change.

**Comment by kpdecker** [comment]
I can't seem to reproduce this. Can you give me step by step instructions?

**Comment by kpdecker** [comment]
Including browser information and any errors that may have been thrown.

**Comment by mostafaeweda** [comment]
In the case there is 2 lines, the first is a complete match and the second is added, the diff lines tell me that the first line was also changed!
Here is the screenshot:
https://www.dropbox.com/s/6o4p4xg1fqis4ze/Screenshot%202015-05-04%2010.20.11.png?dl=0

**Comment by kpdecker** [comment]
The library version on the demo page was out of date. I've updated it with the latest from master and this issue is fixed. Thanks for reporting!
