### ISSUE TITLE
How to preserve links in diffs?

### ISSUE THREAD

**Issue by benji** [kpdecker/jsdiff#567]
Hello, I am trying to find a diffing library that would preserve links in the diff.

For example, I would a change from:
This is a link: https://example.com/123456/list
To:
This is a link: https://example.com/987654/list

To result in the following diff:
Unchanged: `This is a link: `
Removed: `https://example.com/123456/list`
Added: `https://example.com/987654/list`

When trying out jsdiff, this is what I get using the "diffWords":
<img width="943" alt="image" src="https://github.com/user-attachments/assets/2e04f97f-9d3f-4da4-909c-ec704d990968">

Is there a way to maybe customize `intlSegmenter` to achieve this?

**Comment by ExplodingCabbage** [comment]
Hmm. There's no proper support for doing this in an elegant way. One crude/hacky but very easy approach would be to copy and paste `src/diff/word.js` into your project (updating the imports to import from within jsdiff) and tweak `extendedWordChars` in your copy to include `/` as a word character.
