### ISSUE TITLE
diffChars inaccurate

### ISSUE THREAD

**Issue by zhouxin-93** [kpdecker/jsdiff#574]
when using diffChars
"test1 test2 test3<br>test1 test2 test3"

"test1 test2 test3<br>new words"

The above two sentences will cause problems

**Comment by ExplodingCabbage** [comment]
Looks fine to me:

![image](https://github.com/user-attachments/assets/2d4c0ebd-3190-4dba-8454-1fa82351c963)

What's the problem supposed to be?
