### ISSUE TITLE
Support multiple diff hunks

### ISSUE THREAD

**Issue by piranna** [kpdecker/jsdiff#60]
The method ```applyPatch()``` seems only support the first diff hunks, that don't allow to use it when a patch file has several chunks or chunks for several files. First case would be easy to do, just only continue for the next one. For the several files case it would be harder, but how could it be done, specially when you don't know the exact files that need to be patched? Maybe a hash object with the string content of the files, being the paths the key?

**Comment by kpdecker** [comment]
@piranna apply should work with multiple chunks. Can you provide an example of the input and output you are seeing?

It does not support multiple files but there perhaps could be a callback-based API that would allow for something like that without too much effort.

**Comment by piranna** [comment]
> @piranna apply should work with multiple chunks. Can you provide an example of the input and output you are seeing?

I did it only by eye-sign, I've just reviewed it and maybe it wronged me that at https://github.com/kpdecker/jsdiff/blob/5112106376e9716cd1d5665b3530c3ff6a155575/src/patch/apply.js#L25-L30 only it's updated hunks[0], but now I've seen they are being unshifted first, so hunks[0] is new each time, sorry.


> It does not support multiple files but there perhaps could be a callback-based API that would allow for something like that without too much effort.

JsDiff could have a streams of objects that emit a data event for each different file in the original diffStr with the path of the file to be patched and the diffStr fragment that should be applied to that file, so later the user can call to applyPath() with the original file content and the diffStr fragment for that file.

**Comment by kpdecker** [comment]
I'm working on separating the patch apply and parse logic. Once this is done, callers will be able to parse and then iterate over this object if they have multiple files.

**Comment by kpdecker** [comment]
Implemented `applyPatches` which provides a series of callbacks that allow the caller to provide the file data. They are also able to manually call the new `parsePatch` method and iterate over this and then call `applyPatch` directly with the content of each file.

**Comment by piranna** [comment]
Really cool, thank you! :-D

**Comment by kpdecker** [comment]
Released in 2.1.0

**Comment by piranna** [comment]
:+1: :-)
