### ISSUE TITLE
Custom regex

### ISSUE THREAD

**Issue by IonicaBizau** [kpdecker/jsdiff#63]
It would be super nice to allow a custom regex for splitting the words, for example. I need that in one of my projects.

This could be useful when I want to consider words containing special characters (like `.` or so).

**Comment by kpdecker** [comment]
You can do this with a custom override. Take a look at how all of the existing diffs are implemented:

```
  var CssDiff = new Diff(true);
  CssDiff.tokenize = function(value) {
    return removeEmpty(value.split(/([{}:;,]|\s+)/));
  };
```

**Comment by IonicaBizau** [comment]
I know, but how can I call the local `removeEmpty` function, outside of the module?

Thanks!

**Comment by kpdecker** [comment]
Right now you'd need to copy that into your own code. We don't expose that anywhere right now but #64 should make this a bit easier to use once implemented.

**Comment by IonicaBizau** [comment]
@kpdecker Okok, thanks!
