### ISSUE TITLE
Automatically call removeEmpty for all tokenizer calls

### ISSUE THREAD

**Issue by kpdecker** [kpdecker/jsdiff#64]
Right now implementors need to manually perform something like `removeEmpty`. This should be done automatically (but overridable) by the logic calling tokenize.

Issue raised in #63

**Comment by IonicaBizau** [comment]
:+1:

**Comment by kpdecker** [comment]
Released in 2.0.0

**Comment by IonicaBizau** [comment]
Nice! :+1: @kpdecker
