### ISSUE TITLE
cannot require from npm module in node

### ISSUE THREAD

**Issue by commenthol** [kpdecker/jsdiff#67]
The `package.json` file in the published npm version 2.0.1 contains the line `"main": "./lib"`.
As the folder `./lib` is not included in the npm package, the module cannot be required in node after using `npm i diff`.
 
Please change the `package.json` file for the npm package to  `"main": "./dist/diff.js"` or do other smart things.

**Comment by kpdecker** [comment]
Released in 2.0.2

**Comment by kpdecker** [comment]
Sorry about that, it looks like there were some hickups in the new build+publish setup. You should be fine under 2.0.2 now.
