### ISSUE TITLE
Is applyPatches() exposed in the API?

### ISSUE THREAD

**Issue by davidparsson** [kpdecker/jsdiff#73]
I'm trying to use `JsDiff.applyPatches()` on v2.1.0 of your npm package, but i get the error

    TypeError: Object #<Object> has no method 'applyPatches'
        // ...

A quick look at `index.js` indicates that only `applyPatch` is exposed, as I don't see `applyPatches` there:

```JavaScript
import {applyPatch} from './patch/apply';
```

**Comment by kpdecker** [comment]
Thanks for the report. This is an omission. I'll get a release out with this. In the mean time you might be able to link to this using something like `require('diff/lib/patches').applyPatches` depending on module loader you are using.

**Comment by kpdecker** [comment]
Released in 2.1.1
