### ISSUE TITLE
Diffing using {{placeholders}}

### ISSUE THREAD

**Issue by fiznool** [kpdecker/jsdiff#81]
I'd like to be able to diff using `{{placeholders}}`. Below is an example of what I'd like to achieve.

Template:

```
The direct debit of customer {{name}} at {{company}} for £{{amount}} on {{date}} has failed.
```

Input: 

```
The direct debit of customer John Doe at ABC Limited for £60 on 07/10/2015 has failed.
```

Output:

```
{
  name: 'John Doe',
  company: 'ABC Limited',
  amount: '60',
  date: '07/10/2015'
}
```

Using the standard word-based diffing doesn't exactly work, especially in the case of `amount` above (the template key is preceded by '£'), and also if the template key contains any spaces. Therefore I think I need a custom implementation which tokenizes on `{{` and `}}`, but I'm a bit stuck.

Any pointers on how to implement this would be very much appreciated.

**Comment by fiznool** [comment]
In addition to the issues above, I've realised that an input string containing (e.g.) `John at Doe` for the customer name will not parse correctly, the `at` throws it off.

I'm totally ready for a 'this is not what this library is for' answer :-)

**Comment by kpdecker** [comment]
It's an interesting use case. You might be able to do something that tokenizes on both whitespace and the `{{` token pairs. I'm not sure how brittle that will be without jumping in and doing a deep dive which I don't have time for right now.

Glad to accept a PR that does something like this if it's not a huge amount of complexity.

**Comment by kpdecker** [comment]
On second look at this, it seems like this is a problem that is better suited for custom code using regexs.
