### ISSUE TITLE
applyPatches don't use offsets

### ISSUE THREAD

**Issue by piranna** [kpdecker/jsdiff#84]
(Related to https://github.com/kpdecker/jsdiff/issues/82)

While processing https://raw.githubusercontent.com/GregorR/musl-cross/master/patches/gcc-4.7.3-musl.diff with my [pull-request](https://github.com/kpdecker/jsdiff/pull/83) I get some index that couldn't be applied, getting `patched()` callback content equals to `false`. After processing the same file with `patch --verbose -Np1`, it show that this entries are correctly applied but with an offset:

```
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|# HG changeset patch
|# Parent f50bb54f331f73405131a30b4f353cfda1c70304
|Use the generic implementation of libstdc++ primitives when we're on musl, not the glibc one.
|
|diff -r f50bb54f331f libstdc++-v3/configure.host
|--- a/libstdc++-v3/configure.host	Fri Mar 29 16:38:52 2013 -0400
|+++ b/libstdc++-v3/configure.host	Fri Mar 29 16:41:10 2013 -0400
--------------------------
patching file libstdc++-v3/configure.host
Using Plan A...
Hunk #1 succeeded at 243 (offset -21 lines).
Hunk #2 succeeded at 258 (offset -21 lines).
```

Seems `applyPatches()` should try to find the place where the context fit and apply that offset to the patched content, isn't it?

P.D.: don't know if it's related, but at the end of processing the patch file, I get one call to `loadFile()` with `undefined` as index, but ignoring it don't make problems, so maybe it's an extra call that should not be there...

**Comment by piranna** [comment]
> P.D.: don't know if it's related, but at the end of processing the patch file, I get one call to loadFile() with undefined as index, but ignoring it don't make problems, so maybe it's an extra call that should not be there...

[Found and fixed](https://github.com/NodeOS/jsdiff/commit/829e5e086aa24847cc568c666ef068ebea9354f8)!!! :-D

**Comment by kpdecker** [comment]
Have you tried different `fuzzFactor` values?

**Comment by piranna** [comment]
No, I didn't, but according to the source code, seems more related about allowing lines on the context to not be exactly as expected, for example to be able to aply a patch on top of some commits after of the one where it was created.

**Comment by piranna** [comment]
I'll close this since it got already merged.
