### ISSUE TITLE
Highlight whitespace with substitution characters

### ISSUE THREAD

**Issue by robsch** [kpdecker/jsdiff#85]
The library could provide an option to show ↵ for added/removed newlines and · for added/removed blanks.

Do you think this makes sense? I have done it in my application but I'm not sure if this should be part of the jsdiff. It was just an idea.

**Comment by kpdecker** [comment]
The library does this, depending on the mode that you are in, they are just
encoded as the actual white space values. This is a UI request that should
be handled by the application/view layer since so I don't think it quite
fits in this library.

**Comment by robsch** [comment]
You are right. The information is already contained in the diff parts that get returned by e.g. `diffChars()`, even newlines characters if the `newlineIsToke` is set to true.

Anyway, thank you for your library!
