### ISSUE TITLE
Position of difference?

### ISSUE THREAD

**Issue by Eisenspalter** [kpdecker/jsdiff#91]
How can I get the absolute position of the difference?

**Comment by kpdecker** [comment]
Not sure what you mean, can you provide an example?

**Comment by Glench** [comment]
Maybe they mean how can one find the position (e.g. line number) of a difference? I'm trying to use this with codemirror to highlight lines that are different but am having some trouble.

**Comment by pedro93** [comment]
+1 for this.

For example, given this code snippet:
```js
jsdiff.diffChars("please authenticate", "now you may authenticate");
```

The output is:
```js
[ { count: 3, added: undefined, removed: true, value: 'ple' },
  { count: 9, added: true, removed: undefined, value: 'now you m' },
  { count: 1, value: 'a' },
  { count: 2, added: undefined, removed: true, value: 'se' },
  { count: 1, added: true, removed: undefined, value: 'y' },
  { count: 13, value: ' authenticate' } ]
```
With the information given, how can we know where in the initial string ("please authenticate") to apply the diff operations?

**Comment by andrewhead** [comment]
Agreed, +1.  For anyone looking for positions of the "added" substrings, here's a snippet I threw together for my own project, to recover position info (line no. and column) from jsdiff output.  Ymmv given how satisfied you would have been with the underlying diff in the first place. 

Just call `findAddedRanges(before, after)`, passing in your own strings for `before` and `after`.

```javascript
var jsdiff = require('diff');

var before = `
Mary had a little lamb.
Her fleece was white as snow.
`;
var after = `
Mary had a little duck.
Her feathers were brown as mud.
`;


const ranges = findAddedRanges(before, after);

ranges.forEach((range) => {
  console.log(JSON.stringify(range));
});


// Given two strings (`before`, `after`), return a list of all substrings
// that appear in `after` but not in `before`, and the positions of each
// of the substrings within `after`.
function findAddedRanges(before, after) {

  var newRanges = [];
  var lineNumber = 0;
  var column = 0;

  // Compute the diff using `jsdiff`
  const parts = jsdiff.diffChars(before, after);

  // Loop over every part, keeping track of:
  // 1. The current line no. and column in the `after` string
  // 2. Character ranges for all "added" parts in the `after` string
  for (var partIndex = 0; partIndex < parts.length; partIndex++) {

    const part = parts[partIndex];

    // Skip any parts that aren't in `after`
    if (part.removed === true) {
      continue;
    }

    const startLineNumber = lineNumber;
    const startColumn = column;

    // Split the part into lines. Loop throug these lines to find
    // the line no. and column at the end of this part.
    const substring = part.value;
    const lines = substring.split("\n");
    lines.forEach((line, lineIndex) => {
      // The first `line` is actually just a continuation of the last line
      if (lineIndex === 0) {
        column += line.length;
      // All other lines come after a line break.
      } else if (lineIndex > 0) {
        lineNumber += 1;
        column = line.length;
      }
    });

    // Save a range for all of the parts that are only in the `after` string.
    if (part.added === true) {
      newRanges.push({
        startLineNumber: startLineNumber,
        startColumn: startColumn,
        endLineNumber: lineNumber,
        endColumn: column,
        text: part.value
      });
    }
  }
  return newRanges;
}
```

Output from this snippet:

```bash
{"startLineNumber":1,"startColumn":18,"endLineNumber":1,"endColumn":22,"text":"duck"}
{"startLineNumber":2,"startColumn":6,"endLineNumber":2,"endColumn":9,"text":"ath"}
{"startLineNumber":2,"startColumn":10,"endLineNumber":2,"endColumn":11,"text":"r"}
{"startLineNumber":2,"startColumn":15,"endLineNumber":2,"endColumn":17,"text":"re"}
{"startLineNumber":2,"startColumn":18,"endLineNumber":2,"endColumn":24,"text":"brown "}
{"startLineNumber":2,"startColumn":27,"endLineNumber":2,"endColumn":30,"text":"mud"}
```

**Comment by ExplodingCabbage** [comment]
Right now if you want to get a particular change object's start index in either the old text or the new text, you need to loop over the change objects, keeping track of either an index in the old string (that you increment by the `count` of every change object where `added` is falsey) or an index in the new string (that you increment by the `count` of every change object where `removed` is falsey) until you reach the change object you're interested in.

I don't *think* there'd be much value in putting those indexes on the change objects themselves since they can be easily computed via the approach described above if you need them (and keeping the change objects simple has some value).

**Comment by roychowdhuryrohit-dev** [comment]
> Right now if you want to get a particular change object's start index in either the old text or the new text, you need to loop over the change objects, keeping track of either an index in the old string (that you increment by the `count` of every change object where `added` is falsey) or an index in the new string (that you increment by the `count` of every change object where `removed` is falsey) until you reach the change object you're interested in.
> 
> I don't _think_ there'd be much value in putting those indexes on the change objects themselves since they can be easily computed via the approach described above if you need them (and keeping the change objects simple has some value).

Can you please provide an example code snipped for diffChars?
