### ISSUE TITLE
Add ES2015 example to README

### ISSUE THREAD

**Issue by sirbrillig** [kpdecker/jsdiff#96]
The README doesn't explain how to import the functions using the `import` keyword.

That is, something like this won't work (implied by the ES5 node example):

``` javascript
import jsdiff from 'diff';
jsdiff.createPatch(...)
```

But something like this will:

``` javascript
import { createPatch, applyPatch, parsePatch, diffWords } from 'diff';
createPatch(...)
```

**Comment by kpdecker** [comment]
Glad to accept a PR here.
