### ISSUE TITLE
Add documentation to remind Windows users that diff file line endings must be \n and not \r\n

### ISSUE THREAD

**Issue by huan086** [kpdecker/jsdiff#98]
My code was working until I checked in to git. Took a long time to realize that SourceTree (git client) has changed the line endings for the diff file to \r\n because I'm on Windows.

**Comment by kpdecker** [comment]
Do you mean within this repository itself?

**Comment by ExplodingCabbage** [comment]
I'm not really clear on what's being asked for here and it looks like back in 2016 @kpdecker couldn't figure it out either, so I'm gonna close this issue.

(https://github.com/kpdecker/jsdiff/pull/344 will improve jsdiff's handling of Unix vs Windows line endings, though I don't understand this issue enough to figure out if that's actually relevant!)
